### ISSUE TITLE
There is not figgy/_local_tests.py.example

### ISSUE THREAD

**Issue by vaibhavmule** [safarijv/figgy#10]
I'm following README.md and while implementing setup. For running `tox` it is required to have `figgy/_local_tests.py`  but there is not `figgy/_local_tests.py.example` so I could copy make `figgy/_local_tests.py`

**Comment by emilymaier** [comment]
I can't find it either. Are we supposed to use one of the similarly-named files instead?

**Comment by cconcepsbo** [comment]
use your discretion with setting up your local_tests.py

**Comment by jamesyp** [comment]
> use your discretion with setting up your local_tests.py

Do you mean we ought to just write our own tests?

**Comment by vaibhavmule** [comment]
@cconcepsbo Same question from me. Do we have to write our own tests file?

**Comment by jameydeorio** [comment]
This issue has been cleared up by PR https://github.com/safarijv/figgy/pull/12
